### ISSUE TITLE
Problem occurred while setting up the system

### ISSUE THREAD

**Issue by lnalinaf** [rkimoakbioinformatics/oakvar#16]
Hi!
1. I installed oakvar on linux (Ubuntu 20.04.4 LTS) under conda with command "pip install oakvar", then I tried to setup the system with  'ov system setup' and got the problem:
```
No store update to fetch
```
All the packages ``` is already installed ```
```
No module to install found
Problem occurred while setting up the system
```
2. Alternatively trying to install oakvar on linux (Ubuntu 20.04.3 LTS) under micromamba with command "pip install oakvar", and getting the problem:
```
ERROR: Could not find a version that satisfies the requirement oakvar (from versions: none)
ERROR: No matching distribution found for oakvar
```

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 Hi, the problem 2 can be Python version. OakVar requires Python 3.8 or higher. What is your Python version? (Some previous versions of OakVar worked with Python versions below 3.8, and then its requirement changed to Python 3.8 or higher.)

Regarding the problem 1, can you try `ov system setup --clean`? This will try clean installation but will not delete the modules which were already downloaded. Also, what is your OakVar version? (you can find it with `ov version`)

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics, for problem 2 after Python update everything is ok, thanks!
For problem 1, tried `ov system setup --clean`, result is the same 
```
No module to install found
Problem occurred while setting up the system
```
`ov version 2.5.4`

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 I see. I have just published OakVar 2.5.19 which has a possible fix for that (probably there was no real problem with the setup, but the message was shown incorrectly). Please `pip install -U oakvar` to update OakVar and if you run `ov system setup` it will say that no module to install was found, but will not say that a problem occurred anymore. 

There have been some updates to the system modules which fixed some problems, so I'd like to encourage you to run `ov module update` afterwards. 

Let me know if the above work.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics, thanks!
1. After `pip install -U oakvar` version is 2.5.19
2. `ov system setup`:
```
No module to install found
Done setting up the system
```
3. `ov module update`, two modules have been updated, sorry, I did not fix which ones
4. Next, I ran
`ov run example.vcf --vcf2vcf -a clinvar dbSNP -n annotated`
it gave me the error
```
File "/home/user/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/base/vcf2vcf.py", line 303, in run
    res = modules[module_name].annotate(variant)
  File "/home/user/.oakvar/modules/annotators/clinvar/clinvar.py", line 11, in annotate
    self.cursor.execute(
sqlite3.OperationalError: no such table
```
annotated.vcf showed no rsid

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 Based on the error message,it seems that `clinvar` module has not been properly installed. Can you try the following and run the job again?

`ov module install clinvar -f -d -y`
`ov module install dbsnp -f -d -y`

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics, while `ov module install clinvar -f -d -y`:

```
fetching store cache .....

Traceback (most recent call last):
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/webstore/webstore.py", line 144, in make_remote_manifest
    oc_manifest = get_manifest()
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 25, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 636, in get_manifest
    m = module_info(name)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 25, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 227, in module_info
    module_info = RemoteModule("", **info)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/module/remote.py", line 102, in __init__
    self.latest_data_version = self.versions[self.latest_code_version][
KeyError: ''

OakVar store cache has been fetched.

Traceback (most recent call last):
  File "/home/path/anaconda3/envs/py310/bin/ov", line 8, in <module>
    sys.exit(main())
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/__main__.py", line 169, in main
    handle_exception(e)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/__main__.py", line 162, in main
    ret = args.func(args)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/cli/module.py", line 116, in cli_module_install
    return install(args)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/cli/module.py", line 161, in install
    remote_info = get_remote_module_info(module_name, version=version)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/module/remote.py", line 235, in get_remote_module_info
    module_info = remote_module_info_latest_version(module_name)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/__init__.py", line 223, in remote_module_info_latest_version
    module_info = module_info(module_name)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 25, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/store/db.py", line 227, in module_info
    module_info = RemoteModule("", **info)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/module/remote.py", line 102, in __init__
    self.latest_data_version = self.versions[self.latest_code_version][
KeyError: ''
```

dbSNP has not been installed

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 Thanks. The server database had a bug for a few hours, which caused the error you had. I am sorry about that. I am fixing the bug at this moment.

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 The server has been fixed and OakVar v2.5.21 has been released which should be used to use the fix. Below are the steps for the fix.
```
pip install -U oakvar
ov store fetch
ov module install clinvar -f -d -y
ov module install dbsnp -f -d -y
```
Please let me know if this works.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics, many thanks, everything with ok with the updates and fetch, now there is still the error during 
`ov run example.vcf --vcf2vcf -a clinvar -n annotated`

```
Traceback (most recent call last):
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/base/vcf2vcf.py", line 303, in run
    res = modules[module_name].annotate(variant)
  File "/home/path/.oakvar/modules/annotators/clinvar/clinvar.py", line 11, in annotate
    self.cursor.execute(
sqlite3.OperationalError: no such table
```

ov version 2.5.23

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 I see. Does your input file have a chromosome which is not any of `chr1` to `chr22`, `chrX`, `chrY`, and `chrM`? This can cause such an error as the module expects one of those. Please let me know.

Meanwhile, I'll upload a new version of `clinvar` module which will handle such a situation better.

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 I have just released `clinvar` 2022.06.14.1. This version properly handles the chromosomes ClinVar does not support without giving an error. Please try this version.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics right, chromosomes are named without a prefix. Now everything is ok, thanks! Only one noncritical error occurred
```
Traceback (most recent call last):
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/base/vcf2vcf.py", line 298, in run
    res = mapper.map(variant)
  File "/home/path/.oakvar/modules/mappers/gencode/gencode.py", line 1117, in map
    so, achange, cchange, coding = self._get_del_map_data(
  File "/home/path/.oakvar/modules/mappers/gencode/gencode.py", line 2017, in _get_del_map_data
    so, achange = self._get_del_cds_cds_data(
  File "/home/path/.oakvar/modules/mappers/gencode/gencode.py", line 4536, in _get_del_cds_cds_data
    new_ref_codon = _get_bases_tpos(tid, tpos_end + 1, tpos_end + 3)
  File "/home/path/.oakvar/modules/mappers/gencode/gencode.py", line 4829, in _get_bases_tpos
    basebits = (seq[seqbyteno] >> (6 - seqbitno)) & 0b00000011
IndexError: index out of range
```

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 This seems to have been caused by an edge case for the mapper. There should be `.err` file in the directory you ran the job. This file will show which variant caused the error. Can you attach the err file here, or paste a line from the file which shows the error?

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics Sure, .err file content:
```
err.vcf2vcf
[2342842]19     44175027        .       AGGTTG  A       0       RefCall .       GT:GQ:DP:AD:VAF:PL      0/0:43:27:25,2:0.0740741:0,43,55
(index out of range)
```
this is what this and the previous line look like with characters:
```
19^I44175000^I.^IG^IGA^I0^IRefCall^I.^IGT:GQ:DP:AD:VAF:PL^I0/0:49:28:26,2:0.0714286:0,48,67$
19^I44175027^I.^IAGGTTG^IA^I0^IRefCall^I.^IGT:GQ:DP:AD:VAF:PL^I0/0:43:27:25,2:0.0740741:0,43,55$
```

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 Thanks. There were two things. One is that your input is in hg19 coordinate. The other is that GENCODE itself had a rare error. I have just released oakvar 2.5.28. Please update oakvar to this version and try `-l hg19` option with `ov run`. For example,

`ov run input.vcf --vcf2vcf -l hg19 -a clinvar dbsnp`

Regarding the error in GENCODE, it's time to update GENCODE anyway, so I'll update the mapper module to the latest GENCODE (v41) in the near future.

**Comment by rkimoakbioinformatics** [comment]
Also, `--vcf2vcf` can now accept chromosome names with "chr", which is common in VCF format files. Thus, there is no need to add "chr" in input files.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics Thanks! Yes, it's hg19, everything runs smoothly with hg38. 
Launch `ov run input.vcf --vcf2vcf -l hg19 -a clinvar` occasionally gives an error
```
Traceback (most recent call last):
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/base/vcf2vcf.py", line 385, in run
    _, pos, ref, alt = self.liftover(chrom, pos, ref, alt)
  File "/home/path/anaconda3/envs/py310/lib/python3.10/site-packages/oakvar/base/vcf2vcf.py", line 57, in liftover
    raise LiftoverFailure("Liftover failure")
oakvar.exceptions.LiftoverFailure: Liftover failure
```

**Comment by rkimoakbioinformatics** [comment]
Great. The liftover error is expected because some hg19 coordinates do not have hg38 alignments.

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 I have released oakvar v2.5.30 which will not show such stack trace in the log file so that unnecessary alarm will not be raised. The .err file will still show which variants did not have hg38 mapping. Please try the new version.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics .err and .log files are as expected, traceback with LiftoverFailure is sent to stdout, probably, it might be confusing.

**Comment by rkimoakbioinformatics** [comment]
@fkbyf14 Oh, that one. Thanks for letting me know. I have just released oakvar 2.5.31 with a fix for that.

**Comment by lnalinaf** [comment]
@rkimoakbioinformatics it's completely ok! Thanks for your hard work on this.
